security:
    encoders:
        UserBundle\Entity\User: plaintext
        FOS\UserBundle\Model\UserInterface: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: fos_user_security_check
                login_path: /login
                provider: fos_userbundle
                success_handler: login_handler
            logout:
                path: /user/logout
                target: /
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/resetting, role: ROLE_SUPER_ADMIN }
        - { path: ^/associate/, role: ROLE_SUPER_ADMIN }
        - { path: ^/partner/detail/*, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }