superAdminIndex:
    path:   /admin
    defaults: { _controller: UserBundle:Default:SuperAdminIndex }

adminIndex:
    path:   /dashboard
    defaults: { _controller: UserBundle:Default:AdminIndex }

partnerDetail:
    path:   /partner/detail/{id}
    defaults: { _controller: UserBundle:Default:PartnerDetail }

emailingRecap:
    path:   /emailing/recap
    defaults: { _controller: UserBundle:Default:EmailingRecap }

ajaxList:
    path:   /list
    defaults: { _controller: UserBundle:Ajax:List }
    options:
        expose: true

showAddModal:
    path:   /show-add-modal
    defaults: { _controller: UserBundle:Ajax:ShowAddModal }
    options:
        expose: true

addPartnerAjax:
    path:   /add-partner-ajax
    defaults: { _controller: UserBundle:Ajax:AddPartnerAjax }
    options:
        expose: true

deletePartnerAjax:
    path:   /delete-partner
    defaults: { _controller: UserBundle:Ajax:DeletePartnerAjax }
    options:
        expose: true

editPartnerAjax:
    path:   /edit-partner
    defaults: { _controller: UserBundle:Ajax:EditPartnerAjax }
    options:
        expose: true

addPresenceAbsence:
    path:   /add-presence-absence
    defaults: { _controller: UserBundle:Ajax:AddPresenceAbsenceAjax }
    options:
        expose: true

addNewDay:
    path:   /add-new-day
    defaults: { _controller: UserBundle:Ajax:AddNewDayAjax }
    options:
        expose: true