superAdminIndex:
    path:   /admin
    defaults: { _controller: UserBundle:Default:SuperAdminIndex }

partnerDetail:
    path:   /partner/detail/{id}
    defaults: { _controller: UserBundle:Default:PartnerDetail }

partnerIndex:
    path:   /partner
    defaults: { _controller: UserBundle:Default:PartnerIndex }

emailingRecap:
    path:   /emailing/recap
    defaults: { _controller: UserBundle:Default:EmailingRecap }

ajaxList:
    path:   /list
    defaults: { _controller: UserBundle:Ajax:List }
    options:
        expose: true

showAddModal:
    path:   /show-add-modal
    defaults: { _controller: UserBundle:Ajax:ShowAddModal }
    options:
        expose: true

addPartnerAjax:
    path:   /add-partner-ajax
    defaults: { _controller: UserBundle:Ajax:AddPartnerAjax }
    options:
        expose: true

deletePartnerAjax:
    path:   /delete-partner
    defaults: { _controller: UserBundle:Ajax:DeletePartnerAjax }
    options:
        expose: true

editPartnerAjax:
    path:   /edit-partner-ajax
    defaults: { _controller: UserBundle:Ajax:ShowEditModal }
    options:
        expose: true

editPartner:
    path:   /edit-partner
    defaults: { _controller: UserBundle:Ajax:EditPartner }
    options:
        expose: true

monthCallAjax:
    path:   /ajax-month-call
    defaults: { _controller: UserBundle:Ajax:AjaxMonthCall }
    options:
        expose: true

addNewDay:
    path:   /add-new-day
    defaults: { _controller: UserBundle:Ajax:AddNewDayAjax }
    options:
        expose: true

ModalDetailContent:
    path:   /ModalDetailContent
    defaults: { _controller: UserBundle:Ajax:ModalDetailContent }
    options:
        expose: true

validationAjax:
    path:   /validationAjax
    defaults: { _controller: UserBundle:Ajax:ValidationAjax }
    options:
        expose: true

testMail:
    path:   /test-mail
    defaults: { _controller: UserBundle:Default:testMail }

validateDay:
    path:   /validate-day/{dayId}/{validation}/{userId}
    defaults: { _controller: UserBundle:Default:ValidateDay }

Callback:
    path:   /email-callback
    defaults: { _controller: UserBundle:Default:Callback }


